#!/usr/bin/env python

from pyvirtualdisplay import Display
from selenium import webdriver

URL = "https://ds.iris.edu/mda";
print("Fetching Station Data from https://ds.iris.edu/mda...\nPlease ensure you have a stable internet connection for proper execution\n\n")
display = Display(visible=0, size=(800, 600))
display.start()
driver = webdriver.Firefox();
child_driver = webdriver.Firefox();
driver.get(URL)
table = driver.find_elements_by_css_selector("#ptable tr a[href*='mda']")

link_list = [];
row = [];
file_list = [];
f = open('station_list.txt','a')

for i in table:
	link = i.get_attribute('href');
	name = i.text;
	link_list.append(link);
	child_driver.get(link);
	stations = child_driver.find_elements_by_css_selector(".sortable tr td a:last-child")
	sites = child_driver.find_elements_by_css_selector(".sortable tr td:nth-child(2)")
	lats = child_driver.find_elements_by_css_selector(".sortable tr td:nth-child(3)")
	longs = child_driver.find_elements_by_css_selector(".sortable tr td:nth-child(4)")
	elevs = child_driver.find_elements_by_css_selector(".sortable tr td:nth-child(5)")
	f_starts = child_driver.find_elements_by_css_selector(".sortable tr td:nth-child(6)")
	l_ends = child_driver.find_elements_by_css_selector(".sortable tr td:nth-child(7)")
	n_stations = len(stations)

	for j in range(0,(n_stations)):
		array = name.encode('ascii','ignore')
		station = stations[j].text.encode('ascii','ignore')
		site = sites[j].text.encode('ascii','ignore')
		lat = lats[j].text.encode('ascii','ignore')
		longt = longs[j].text.encode('ascii','ignore')
		elev = elevs[j].text.encode('ascii','ignore')
		f_start = f_starts[j].text.encode('ascii','ignore')
		l_end = l_ends[j].text.encode('ascii','ignore')
		if (len(array)>0 and len(station)>0):
			print(array+" "+station+" ("+site+") "+lat+" "+longt+" "+elev+" "+f_start+" "+l_end)
			row = [array,station,lat,longt,elev]
			file_list.append(row);
			f.write(array+" "+station+" "+lat+" "+longt+" "+elev+" "+f_start+" "+l_end+"\n");

f.close();
driver.close();
child_driver.close();
display.stop()